org.gradle.jvmargs=-Xmx4096M

mod_id = immersive_weathering
mod_version = 1.21.1-2.1.0
maven_group = com.ordana
enabled_platforms = fabric,neoforge

minecraft_version = 1.21.1

parchment_version = 1.21.1:2024.11.17

fabric_loader_version = 0.16.9
fabric_api_version = 0.116.6+1.21.1

neoforge_version = 21.1.77

modmenu_version = 11.0.3
cloth_version = 15.0.140
emi_version = 1.1.21+1.21.1
moonlight_version = 1.21-2.29.20
moonlight_fabric_modrinth_version = nOYRAzG7
moonlight_neoforge_modrinth_version = X7j32itX
